packages:
  - ansible
  - docker
  - kubectl
  - helm
  - terraform=1.1.7
  - nomad
  - consul
  - azure-cli
  - awscli
  # - google-cloud-cli
  - telnet.x86_64
repositories:
  - hashicorp
  - microsoft
  # - google
binaries:
  github:
    - remotemobprogramming/mob=linux_amd64=v3.2.0
    - derailed/k9s=Linux_x86_64
requirements:
  pip:
    - packaging
    - requests[security]
    - xmltodict
    - azure-cli-core=2.34.0
    - azure-common=1.1.11
  ansible:
    roles:
      - t_systems_mms.grafana
    collections:
      - t_systems_mms.acme=2.3.1
      - t_systems_mms.icinga_director=1.28.0
extensions:
  az:
    - front-door=1.0.15
  helm:
    - https://github.com/databus23/helm-diff=3.5.0
    - https://github.com/jkroepke/helm-secrets
