---
stages:
  - build_dmc

variables:
  CONTAINER_IMAGE_MGMT: $CI_REGISTRY_IMAGE/service-mgmt:latest

.docker-login: &docker-login
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

# build management-container
build_service-mgmt:
  stage: build_dmc
  image: $DOCKERHUB_MIRROR/docker:git
  services:
    - name: $DOCKERHUB_MIRROR/docker:dind
      alias: docker
  script:
    # clone DMC repo from GitHub
    - git clone --recursive --branch ${GITHUB_DMC_TAG} --depth 1 https://github.com/T-Systems-MMS/docker-management-container $CI_PROJECT_DIR/docker/docker-management-container
    # get date for tagging the image
    - export DATE=$(date +"%F")
    # create Dockerfile with template from DMC repo
    - sh $CI_PROJECT_DIR/docker/docker-management-container/render.sh $CI_PROJECT_DIR/docker/service-mgmt
    # build and tag image
    - docker build -t $DMC_IMAGE:${DATE} docker/service-mgmt
    - docker tag $DMC_IMAGE:${DATE} $DMC_IMAGE:latest
    # push all images
    - docker push --all-tags $DMC_IMAGE
  extends: 
    - .docker_login
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $JOB == "build_dmc"
