---
name: Create and publish Docker image

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: T-Systems-MMS/dmc

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: github.ref == 'refs/heads/master'

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        if: github.ref == 'refs/heads/master'

      - name: build Dockerfile min_build
        run: cp examples/min_build.yaml ./build.yaml && sh render.sh .

      - name: Build and push dmc:min
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          push: false
          tags: min

      - name: Test $IMAGE_NAME:min
        run: |
          docker run --rm dmc:min

      - name: Build and push dmc:full
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          push: false
          tags: $IMAGE_NAME:full

      - name: Test dmc:full
        run: |
          docker run --rm dmc:full
