---
name: Create and publish Docker image

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: T-Systems-MMS/dmc

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        example:
          - min
          - full

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: github.ref == 'refs/heads/master'

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        if: github.ref == 'refs/heads/master'

      - name: build Dockerfile ${{ matrix.example }}
        run: cp examples/${{ matrix.example }}_build.yaml ./build.yaml && sh render.sh .

      - name: Build and push dmc:${{ matrix.example }}
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          push: false
          tags: dmc:${{ matrix.example }}

      - name: Test $IMAGE_NAME:${{ matrix.example }}
        run: |
          docker run --rm dmc:${{ matrix.example }}

      - name: Build and push dmc:${{ matrix.example }}
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          push: true
          tags: ${{ matrix.example }}
        if: github.ref == 'refs/heads/master'
