---
name: linting

on: [push, pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run ShellCheck
        uses: azohra/shell-linter@latest
        with:
          path: "*.sh"

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.0.0
        with:
          dockerfile: Dockerfile.template
          ignore: DL3009,DL3013,SC2001,SC2068
          # DL3013 - solved over sed command
